[platformio]
src_dir = .

[env:pico_w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
lib_deps =
  arminjo/ServoEasing @ ^3.3.3
  sparkfun/SparkFun APDS9960 RGB and Gesture Sensor @ ^1.4.3
monitor_speed = 9600
